services:
  themerr-normalize:
    image: themerr-normalize
    container_name: themerr-normalize
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - SLEEP_DURATION=43200
      - MEDIA_PATH=/media
    volumes:
      - ${MEDIA_PATH}:/media
    restart: unless-stopped