services:
  themerr-normalize:
    image: themerr-normalize
    container_name: themerr-normalize
    environment:
      - SLEEP_DURATION=43200
      - MEDIA_PATH=/media
    volumes:
      - ${MEDIA_PATH}:/media
    user: ${PUID}:${PGID}
    restart: unless-stopped
